In [1]:
import pandas as pd
import numpy as np
import os
import sys
import urllib.request
import json
import seaborn as sns
import warnings
import datetime
import matplotlib.pyplot as plt
import set_matplotlib_hangul

warnings.simplefilter("ignore")

Hangul OK in your Windows !!!

In [2]:
# 네이버 api id,pw
client_id = "jOc7UxR_Sp1MMk2mwOq1"
client_secret = "s9PY8Vl3Wz"

In [3]:
def gen_search_url(search_text, start_num, disp_num):
    base = "https://openapi.naver.com/v1/search"
    node = "/book_adv.json" 
    param_title = "?d_titl=" + urllib.parse.quote(search_text)
    param_start = "&start=" + str(start_num)
    param_disp = "&display=" + str(disp_num)
    param_catg = "&d_catg=280" # 컴퓨터/IT 카테고리 넘버 = 280
    
    return base + node + param_title + param_start + param_disp + param_catg

In [4]:
def get_result_onpage(url):
    request = urllib.request.Request(url)
    request.add_header("X-Naver-Client-Id", client_id)
    request.add_header("X-Naver-Client-Secret", client_secret)
    response = urllib.request.urlopen(request)
    rescode = response.getcode()
    print("[%s] Url Request Success" % datetime.datetime.now())
    print(response, response.getcode(), response.code, response.status) 
    return json.loads(response.read().decode("utf-8"))

In [5]:
def delete_tag(input_str):
    input_str = input_str.replace("<b>", "")
    input_str = input_str.replace("</b>", "")
    return input_str

In [6]:
def get_fields(json_data):
    title = [delete_tag(each["title"]) for each in json_data["items"]]
    link = [each["link"] for each in json_data["items"]]
    author = [each["author"] for each in json_data["items"]]
    price = [each["price"] for each in json_data["items"]]
    discount = [each["discount"] for each in json_data["items"]]
    publisher = [each["publisher"] for each in json_data["items"]]
    isbn = [each["isbn"] for each in json_data["items"]]
    pubdate = [each["pubdate"] for each in json_data["items"]]
    result_pd = pd.DataFrame({
        "제목": title, 
        "링크": link, 
        "저자": author, 
        "가격": price,
        "할인 가격": discount,
        "isbn": isbn,
        "출판사": publisher,
        '출간일': pubdate
        
    }, columns=["제목", "저자", "출판사", "가격", "할인 가격", "출간일", "isbn", "링크"])
    return result_pd

In [7]:
langs = ['Assembly language', 'Classic Visual Basic', 'Go', 'MATLAB', '매트랩', 'Groovy', '그루비', 'Ruby', '루비', 'Swift', '스위프트', 'Fortran', '포트란', 'Perl', '펄', 'Delphi', '델파이']

def search_func(name):
    result_lang = []
    for n in range(1, 1000, 100):
        url = gen_search_url(name, n, 100)
        json_result = get_result_onpage(url)
        pd_result = get_fields(json_result)
        pd_result['검색명'] = '{}'.format(name)
        result_lang.append(pd_result)
    result_lang = pd.concat(result_lang)
    return result_lang

In [8]:
langs_list = [] 

for i in range(len(langs)):
    langs_list.append(search_func(langs[i]))

[2021-10-24 21:59:10.443797] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BC6430> 200 200 200
[2021-10-24 21:59:10.536689] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3EE50> 200 200 200
[2021-10-24 21:59:10.625015] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C22F40> 200 200 200
[2021-10-24 21:59:10.728071] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31550> 200 200 200
[2021-10-24 21:59:10.881401] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31850> 200 200 200
[2021-10-24 21:59:11.014952] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C316A0> 200 200 200
[2021-10-24 21:59:11.145426] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31AC0> 200 200 200
[2021-10-24 21:59:11.263565] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31430> 200 200 200
[2021-10-24 21:59:11.397274] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B6A0> 200 200 200
[2021-10-24 21:59:11.536652] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31400> 200 200 200
[2021-10-24 21:59:11.655783] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3EEB0> 200 200 200
[2021-10-24 21:59:11.755052] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C22F70> 200 200 200
[2021-10-24 21:59:11.914518] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3E3D0> 200 200 200
[2021-10-24 21:59:12.042090] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31B80> 200 200 200
[2021-10-24 21:59:12.164793] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C311C0> 200 200 200
[2021-10-24 21:59:12.265978] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31DC0> 200 200 200
[2021-10-24 21:59:12.412309] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31C40> 200 200 200
[2021-10-24 21:59:12.549854] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31F40> 200 200 200
[2021-10-24 21:59:12.628584] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3BD60> 200 200 200
[2021-10-24 21:59:12.756996] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3BD00> 200 200 200
[2021-10-24 21:59:13.119698] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C22F70> 200 200 200
[2021-10-24 21:59:13.277630] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C22F40> 200 200 200
[2021-10-24 21:59:13.373311] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31790> 200 200 200
[2021-10-24 21:59:13.528834] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C22F10> 200 200 200
[2021-10-24 21:59:13.696229] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31FA0> 200 200 200
[2021-10-24 21:59:13.836807] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31F40> 200 200 200
[2021-10-24 21:59:13.978483] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C317F0> 200 200 200
[2021-10-24 21:59:14.129975] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C316D0> 200 200 200
[2021-10-24 21:59:14.283459] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31850> 200 200 200
[2021-10-24 21:59:14.423988] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B2E0> 200 200 200
[2021-10-24 21:59:14.856547] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3EB80> 200 200 200
[2021-10-24 21:59:15.269809] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3EBE0> 200 200 200
[2021-10-24 21:59:15.411685] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31FD0> 200 200 200
[2021-10-24 21:59:15.554208] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3EAF0> 200 200 200
[2021-10-24 21:59:15.687903] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31790> 200 200 200
[2021-10-24 21:59:15.806369] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31AC0> 200 200 200
[2021-10-24 21:59:15.934523] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31D30> 200 200 200
[2021-10-24 21:59:16.076464] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31EB0> 200 200 200
[2021-10-24 21:59:16.248123] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B4C0> 200 200 200
[2021-10-24 21:59:16.388004] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B2E0> 200 200 200
[2021-10-24 21:59:16.628857] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BFF2E0> 200 200 200
[2021-10-24 21:59:16.776822] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C22F40> 200 200 200
[2021-10-24 21:59:16.900377] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8B747C0> 200 200 200
[2021-10-24 21:59:17.038973] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C313D0> 200 200 200
[2021-10-24 21:59:17.194190] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31280> 200 200 200
[2021-10-24 21:59:17.369459] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31880> 200 200 200
[2021-10-24 21:59:17.509790] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31A00> 200 200 200
[2021-10-24 21:59:17.678906] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B8B0> 200 200 200
[2021-10-24 21:59:17.795848] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3BF10> 200 200 200
[2021-10-24 21:59:17.938605] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3BCD0> 200 200 200
[2021-10-24 21:59:18.105048] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8B747C0> 200 200 200
[2021-10-24 21:59:18.245174] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C22FD0> 200 200 200
[2021-10-24 21:59:18.388952] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3EE80> 200 200 200
[2021-10-24 21:59:18.543965] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31FA0> 200 200 200
[2021-10-24 21:59:18.703088] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C313D0> 200 200 200
[2021-10-24 21:59:18.830032] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31400> 200 200 200
[2021-10-24 21:59:18.974785] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3BC70> 200 200 200
[2021-10-24 21:59:19.110319] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B1F0> 200 200 200
[2021-10-24 21:59:19.264802] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BAE280> 200 200 200
[2021-10-24 21:59:19.406951] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B8B0> 200 200 200
[2021-10-24 21:59:19.558821] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C22FD0> 200 200 200
[2021-10-24 21:59:19.721277] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3EE50> 200 200 200
[2021-10-24 21:59:19.864044] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C22F70> 200 200 200
[2021-10-24 21:59:20.009352] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31C10> 200 200 200
[2021-10-24 21:59:20.146198] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31640> 200 200 200
[2021-10-24 21:59:20.294864] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31D00> 200 200 200
[2021-10-24 21:59:20.466916] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B2E0> 200 200 200
[2021-10-24 21:59:20.624812] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3BCD0> 200 200 200
[2021-10-24 21:59:20.769792] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B790> 200 200 200
[2021-10-24 21:59:20.900354] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3BEB0> 200 200 200
[2021-10-24 21:59:21.056874] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C22F70> 200 200 200
[2021-10-24 21:59:21.219841] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3E3D0> 200 200 200

[2021-10-24 21:59:21.368373] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3EE80> 200 200 200
[2021-10-24 21:59:21.503251] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31C10> 200 200 200
[2021-10-24 21:59:21.644270] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31970> 200 200 200
[2021-10-24 21:59:21.797013] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BAE0A0> 200 200 200
[2021-10-24 21:59:21.970179] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BBA640> 200 200 200
[2021-10-24 21:59:22.122592] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B5E0> 200 200 200
[2021-10-24 21:59:22.283147] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3BF10> 200 200 200
[2021-10-24 21:59:22.398677] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B7C0> 200 200 200
[2021-10-24 21:59:22.596456] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C22F70> 200 200 200
[2021-10-24 21:59:22.748512] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3EAF0> 200 200 200
[2021-10-24 21:59:22.919700] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C22F40> 200 200 200
[2021-10-24 21:59:23.069294] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C22F70> 200 200 200
[2021-10-24 21:59:23.202048] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C316D0> 200 200 200
[2021-10-24 21:59:23.328339] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31B80> 200 200 200
[2021-10-24 21:59:23.491791] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BBA640> 200 200 200
[2021-10-24 21:59:23.632318] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B3D0> 200 200 200
[2021-10-24 21:59:23.796348] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C43BB0> 200 200 200
[2021-10-24 21:59:23.950255] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C43190> 200 200 200
[2021-10-24 21:59:24.157756] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3EB80> 200 200 200
[2021-10-24 21:59:24.294106] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BAE280> 200 200 200
[2021-10-24 21:59:24.436445] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BAE1F0> 200 200 200
[2021-10-24 21:59:24.574485] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31730> 200 200 200
[2021-10-24 21:59:24.736830] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31FA0> 200 200 200
[2021-10-24 21:59:24.887646] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31FD0> 200 200 200
[2021-10-24 21:59:25.026182] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B790> 200 200 200
[2021-10-24 21:59:25.148617] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C43EB0> 200 200 200
[2021-10-24 21:59:25.293733] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C43B80> 200 200 200
[2021-10-24 21:59:25.445133] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3BAF0> 200 200 200
[2021-10-24 21:59:25.695536] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BBA610> 200 200 200
[2021-10-24 21:59:25.859187] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C22F40> 200 200 200
[2021-10-24 21:59:26.013249] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3EC10> 200 200 200
[2021-10-24 21:59:26.141819] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31850> 200 200 200
[2021-10-24 21:59:26.284731] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31A90> 200 200 200
[2021-10-24 21:59:26.440521] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B4F0> 200 200 200
[2021-10-24 21:59:26.575235] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B4F0> 200 200 200
[2021-10-24 21:59:26.700253] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B2E0> 200 200 200
[2021-10-24 21:59:26.845813] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C434C0> 200 200 200
[2021-10-24 21:59:26.999981] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C43070> 200 200 200
[2021-10-24 21:59:27.347992] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C22F70> 200 200 200
[2021-10-24 21:59:27.648136] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BAE250> 200 200 200
[2021-10-24 21:59:27.859131] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3E130> 200 200 200
[2021-10-24 21:59:28.000788] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31C10> 200 200 200
[2021-10-24 21:59:28.149657] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31D00> 200 200 200
[2021-10-24 21:59:28.301777] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3BCD0> 200 200 200
[2021-10-24 21:59:28.435116] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31880> 200 200 200
[2021-10-24 21:59:28.586718] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B430> 200 200 200
[2021-10-24 21:59:28.721337] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C43B80> 200 200 200
[2021-10-24 21:59:28.849837] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8CAE3D0> 200 200 200
[2021-10-24 21:59:29.020270] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BBA640> 200 200 200
[2021-10-24 21:59:29.177707] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3EC10> 200 200 200
[2021-10-24 21:59:29.308330] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C22F10> 200 200 200
[2021-10-24 21:59:29.438894] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3EBE0> 200 200 200
[2021-10-24 21:59:29.565593] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31880> 200 200 200
[2021-10-24 21:59:29.700155] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B1F0> 200 200 200
[2021-10-24 21:59:29.848275] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C43070> 200 200 200
[2021-10-24 21:59:29.981776] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8CAE4C0> 200 200 200
[2021-10-24 21:59:30.136330] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C43310> 200 200 200
[2021-10-24 21:59:30.294729] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8CAEFD0> 200 200 200
[2021-10-24 21:59:30.498047] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BBA730> 200 200 200
[2021-10-24 21:59:30.626692] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BAE250> 200 200 200
[2021-10-24 21:59:30.770139] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3EE50> 200 200 200
[2021-10-24 21:59:30.924621] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31EB0> 200 200 200
[2021-10-24 21:59:31.065152] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31790> 200 200 200
[2021-10-24 21:59:31.203777] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B3D0> 200 200 200
[2021-10-24 21:59:31.335159] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C434C0> 200 200 200
[2021-10-24 21:59:31.463659] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C43EB0> 200 200 200
[2021-10-24 21:59:31.594222] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8CAE400> 200 200 200
[2021-10-24 21:59:31.735877] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8D0C070> 200 200 200
[2021-10-24 21:59:31.899012] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BBA730> 200 200 200
[2021-10-24 21:59:32.049699] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BAE250> 200 200 200
[2021-10-24 21:59:32.211188] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3EC10> 200 200 200
[2021-10-24 21:59:32.339730] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3BEB0> 200 200 200

[2021-10-24 21:59:32.477278] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C312E0> 200 200 200
[2021-10-24 21:59:32.601199] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C43070> 200 200 200
[2021-10-24 21:59:32.718463] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C43550> 200 200 200
[2021-10-24 21:59:32.847836] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8CAE6D0> 200 200 200
[2021-10-24 21:59:32.976777] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8CAE400> 200 200 200
[2021-10-24 21:59:33.102640] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C43550> 200 200 200
[2021-10-24 21:59:33.372052] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BFF2E0> 200 200 200
[2021-10-24 21:59:33.508582] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BBA640> 200 200 200
[2021-10-24 21:59:33.616234] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BAE070> 200 200 200
[2021-10-24 21:59:33.734422] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BBA640> 200 200 200
[2021-10-24 21:59:33.893391] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3E3D0> 200 200 200
[2021-10-24 21:59:34.028946] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C43EB0> 200 200 200
[2021-10-24 21:59:34.165490] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8CAEA00> 200 200 200
[2021-10-24 21:59:34.286367] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8CAE4C0> 200 200 200
[2021-10-24 21:59:34.419320] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8CAEFD0> 200 200 200
[2021-10-24 21:59:34.550894] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8CAE310> 200 200 200
[2021-10-24 21:59:34.926411] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C22F10> 200 200 200
[2021-10-24 21:59:35.096154] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BAE1F0> 200 200 200
[2021-10-24 21:59:35.237709] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3B2E0> 200 200 200
[2021-10-24 21:59:35.396527] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C3E3D0> 200 200 200
[2021-10-24 21:59:35.544209] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8C31EB0> 200 200 200
[2021-10-24 21:59:35.664711] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B3BAE070> 200 200 200
[2021-10-24 21:59:35.794762] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8CAE0A0> 200 200 200
[2021-10-24 21:59:35.902908] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8CAE790> 200 200 200
[2021-10-24 21:59:36.074896] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8D0CB20> 200 200 200
[2021-10-24 21:59:36.266198] Url Request Success
<http.client.HTTPResponse object at 0x000001A2B8D0CE50> 200 200 200

In [9]:
langs_list[0].head(3)

,제목,저자,출판사,가격,할인 가격,출간일,isbn,링크,검색명
0,ASSEMBLY LANGUAGE,김행곤,청문각(교문사),17000,,19980905,8970885293 9788970885292,http://book.naver.com/bookdb/book_detail.php?b...,Assembly language
1,ADVANCED ASSEMBLY LANGUAGE,Steven Holzner,영진닷컴,18000,,19930601,8931405197 9788931405194,http://book.naver.com/bookdb/book_detail.php?b...,Assembly language
2,ADVANCED ASSEMBLY LANGUAGE,Steven Holzner,영진닷컴,18000,,19930601,8931402619 9788931402612,http://book.naver.com/bookdb/book_detail.php?b...,Assembly language

In [10]:
langs_list[len(langs_list) - 1].head(3)

,제목,저자,출판사,가격,할인 가격,출간일,isbn,링크,검색명
0,시작하는 사람들을 위한 델파이 프로그래밍 (생각하면서 처음부터 제대로 시작하는 프로...,유리 칼미코프,데브기어출판부,12000,10800,20160421,8996251666 9788996251668,http://book.naver.com/bookdb/book_detail.php?b...,델파이
1,델파이 프로그래밍 언어 (Delphi Programming Language),엠바카데로 테크놀로지,데브기어출판부,18000,16200,20090401,8993000158 9788993000153,http://book.naver.com/bookdb/book_detail.php?b...,델파이
2,"안드로이드 iOS앱 with 델파이 1 (한 번에 개발하는,기초다지기)",김원경|김현수|오상현,데브기어출판부,10000,9000,20141020,899625164X 9788996251644,http://book.naver.com/bookdb/book_detail.php?b...,델파이

In [11]:
langs_df2 = pd.concat(langs_list,ignore_index=True) # 인덱스 재정렬
langs_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 809 entries, 0 to 808
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   제목      809 non-null    object
 1   저자      809 non-null    object
 2   출판사     809 non-null    object
 3   가격      809 non-null    object
 4   할인 가격   809 non-null    object
 5   출간일     809 non-null    object
 6   isbn    809 non-null    object
 7   링크      809 non-null    object
 8   검색명     809 non-null    object
dtypes: object(9)
memory usage: 57.0+ KB

In [12]:
langs_df2.head(3)

,제목,저자,출판사,가격,할인 가격,출간일,isbn,링크,검색명
0,ASSEMBLY LANGUAGE,김행곤,청문각(교문사),17000,,19980905,8970885293 9788970885292,http://book.naver.com/bookdb/book_detail.php?b...,Assembly language
1,ADVANCED ASSEMBLY LANGUAGE,Steven Holzner,영진닷컴,18000,,19930601,8931405197 9788931405194,http://book.naver.com/bookdb/book_detail.php?b...,Assembly language
2,ADVANCED ASSEMBLY LANGUAGE,Steven Holzner,영진닷컴,18000,,19930601,8931402619 9788931402612,http://book.naver.com/bookdb/book_detail.php?b...,Assembly language

In [13]:
langs_df2.tail(3)

,제목,저자,출판사,가격,할인 가격,출간일,isbn,링크,검색명
806,알기쉬운 델파이 2.0,주병진,정보문화사,18000,,19961109,897627282X 9788976272829,http://book.naver.com/bookdb/book_detail.php?b...,델파이
807,정보처리산업기사 실기 (델파이),주병진,정보문화사,10000,,19990111,8976275284 9788976275288,http://book.naver.com/bookdb/book_detail.php?b...,델파이
808,델파이 2 (21일완성),DAN OSIER,인포북,18000,,19970610,8980542712 9788980542710,http://book.naver.com/bookdb/book_detail.php?b...,델파이

- 데이터를 정상적으로 불러왔다.

#### 한글명과 영문명이 있는 언어들의 검색명을 통일시키자.

In [14]:
langs_df2['검색명'].unique()

array(['Assembly language', 'Go', 'MATLAB', '매트랩', '그루비', 'Ruby', '루비',
       'Swift', '스위프트', 'Fortran', '포트란', 'Perl', '펄', 'Delphi', '델파이'],
      dtype=object)

#### 그루비 => Groovy로 이름 변경

In [15]:
len(langs_df2[langs_df2['검색명'] == '그루비'])

2

In [16]:
langs_df2.loc[langs_df2['검색명'] == '그루비', '검색명'] = 'Groovy'

In [17]:
len(langs_df2[langs_df2['검색명'] == 'Groovy'])

2

#### MATLAB, 매트랩 => MATLAB

In [18]:
len(langs_df2[langs_df2['검색명'] == 'MATLAB'])

187

In [19]:
len(langs_df2[langs_df2['검색명'] == '매트랩'])

32

In [20]:
langs_df2.loc[langs_df2['검색명'] == '매트랩', '검색명'] = 'MATLAB'

In [21]:
len(langs_df2[langs_df2['검색명'] == 'MATLAB'])

219

#### Ruby, 루비 => Ruby

In [22]:
len(langs_df2[langs_df2['검색명'] == 'Ruby'])

11

In [23]:
len(langs_df2[langs_df2['검색명'] == '루비'])

14

In [24]:
langs_df2.loc[langs_df2['검색명'] == '루비', '검색명'] = 'Ruby'

In [25]:
len(langs_df2[langs_df2['검색명'] == 'Ruby'])

25

#### Swift, 스위프트 => Swift

In [26]:
len(langs_df2[langs_df2['검색명'] == 'Swift'])

29

In [27]:
len(langs_df2[langs_df2['검색명'] == '스위프트'])

33

In [28]:
langs_df2.loc[langs_df2['검색명'] == '스위프트', '검색명'] = 'Swift'

In [29]:
len(langs_df2[langs_df2['검색명'] == 'Swift'])

62

#### Fortran, 포트란 => Fortran

In [30]:
len(langs_df2[langs_df2['검색명'] == 'Fortran'])

237

In [31]:
len(langs_df2[langs_df2['검색명'] == '포트란'])

16

In [32]:
langs_df2.loc[langs_df2['검색명'] == '포트란', '검색명'] = 'Fortran'

In [33]:
len(langs_df2[langs_df2['검색명'] == 'Fortran'])

253

#### Perl, 펄 => Perl

In [34]:
len(langs_df2[langs_df2['검색명'] == 'Perl'])

29

In [35]:
len(langs_df2[langs_df2['검색명'] == '펄'])

8

In [36]:
langs_df2.loc[langs_df2['검색명'] == '펄', '검색명'] = 'Perl'

In [37]:
len(langs_df2[langs_df2['검색명'] == 'Perl'])

37

#### Delphi, 델파이 => Delphi

In [38]:
len(langs_df2[langs_df2['검색명'] == 'Delphi'])

44

In [39]:
len(langs_df2[langs_df2['검색명'] == '델파이'])

101

In [40]:
langs_df2.loc[langs_df2['검색명'] == '델파이', '검색명'] = 'Delphi'

In [41]:
len(langs_df2[langs_df2['검색명'] == 'Delphi'])

145

#### 중복된 책들을 수집한 isbn정보로 정리하자.

In [42]:
len(langs_df2['isbn'].unique())

777

- 중복된 데이터를 제외한 책의 수

In [43]:
len(langs_df2) - len(langs_df2['isbn'].unique())

32

- 중복된 책의 수

In [44]:
langs_df2.drop_duplicates(subset='isbn', keep='first', inplace=True)
langs_df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 777 entries, 0 to 808
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   제목      777 non-null    object
 1   저자      777 non-null    object
 2   출판사     777 non-null    object
 3   가격      777 non-null    object
 4   할인 가격   777 non-null    object
 5   출간일     777 non-null    object
 6   isbn    777 non-null    object
 7   링크      777 non-null    object
 8   검색명     777 non-null    object
dtypes: object(9)
memory usage: 60.7+ KB

- 중복된 책들을 정리하였으므로, 다시 인덱스를 재정렬해준다.

In [45]:
langs_df2.reset_index(drop=True, inplace=True)
langs_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   제목      777 non-null    object
 1   저자      777 non-null    object
 2   출판사     777 non-null    object
 3   가격      777 non-null    object
 4   할인 가격   777 non-null    object
 5   출간일     777 non-null    object
 6   isbn    777 non-null    object
 7   링크      777 non-null    object
 8   검색명     777 non-null    object
dtypes: object(9)
memory usage: 54.8+ KB

In [46]:
langs_df2['검색명'].unique()

array(['Assembly language', 'Go', 'MATLAB', 'Groovy', 'Ruby', 'Swift',
       'Fortran', 'Perl', 'Delphi'], dtype=object)

In [47]:
langs_df2.rename(columns={'검색명': '언어'}, inplace=True) # 인덱스 이름에 대한 가시성을 위해 검색명을 언어로 바꾼다.
langs_df2.columns.unique()

Index(['제목', '저자', '출판사', '가격', '할인 가격', '출간일', 'isbn', '링크', '언어'], dtype='object')

#### 가격과 할인 가격의 데이터타입을 정수형으로 변환해주자.

In [48]:
langs_df2['가격'] = pd.to_numeric(langs_df2['가격'])
langs_df2['할인 가격'] = pd.to_numeric(langs_df2['할인 가격'])
langs_df2['출간일'] = pd.to_datetime(langs_df2['출간일'],errors='coerce')
langs_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   제목      777 non-null    object
 1   저자      777 non-null    object
 2   출판사     777 non-null    object
 3   가격      777 non-null    int64
 4   할인 가격   178 non-null    float64
 5   출간일     777 non-null    datetime64[ns]
 6   isbn    777 non-null    object
 7   링크      777 non-null    object
 8   언어      777 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(1), object(6)
memory usage: 54.8+ KB

- 형변환을 하고보니 할인 가격이 없는 값들이 있는 것 같아서 처리해줘야겠다.

In [49]:
langs_df2['할인 가격2'] = np.where(pd.notnull(langs_df2['할인 가격']) == True, langs_df2['할인 가격'], langs_df2['가격'])

- 할인 가격이 없는 값들은 할인을 하지 않는다고 생각하고 모두 정가격으로 값을 채워주었다.

In [50]:
langs_df2['할인 가격'] = langs_df2['할인 가격2']

In [51]:
del langs_df2['할인 가격2']

In [52]:
langs_df2.isnull().sum()

제목       0
저자       0
출판사      0
가격       0
할인 가격    0
출간일      0
isbn     0
링크       0
언어       0
dtype: int64

In [53]:
langs_df2[['가격', '할인 가격']] = langs_df2[['가격', '할인 가격']].astype('int')
langs_df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 9 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   제목      777 non-null    object
 1   저자      777 non-null    object
 2   출판사     777 non-null    object
 3   가격      777 non-null    int32
 4   할인 가격   777 non-null    int32
 5   출간일     777 non-null    datetime64[ns]
 6   isbn    777 non-null    object
 7   링크      777 non-null    object
 8   언어      777 non-null    object
dtypes: datetime64[ns](1), int32(2), object(6)
memory usage: 48.7+ KB

#### 상위 10개 언어 관련 도서 데이터와 병합을 위해 연도별 컬럼도 추가해주자.

In [54]:
langs_df2['출간년도'] = langs_df2['출간일'].dt.year
langs_df2.tail(3)

,제목,저자,출판사,가격,할인 가격,출간일,isbn,링크,언어,출간년도
774,알기쉬운 델파이 2.0,주병진,정보문화사,18000,18000,1996-11-09,897627282X 9788976272829,http://book.naver.com/bookdb/book_detail.php?b...,Delphi,1996
775,정보처리산업기사 실기 (델파이),주병진,정보문화사,10000,10000,1999-01-11,8976275284 9788976275288,http://book.naver.com/bookdb/book_detail.php?b...,Delphi,1999
776,델파이 2 (21일완성),DAN OSIER,인포북,18000,18000,1997-06-10,8980542712 9788980542710,http://book.naver.com/bookdb/book_detail.php?b...,Delphi,1997

#### 이제 앞전의 상위 10개 언어 관련 도서 데이터와 병합을 하기 위해 먼저 csv로 저장한 데이터를 불러오자.

In [55]:
langs_df = pd.read_csv('../data/langs_df.csv', encoding='euc-kr', sep=',', index_col=0)
langs_df.tail(3)

,제목,저자,출판사,가격,할인 가격,출간일,isbn,링크,언어,출간년도
6419,INSIDE SECRETS JAVASCRIPT,James Jaworski,삼각형,40000,40000,1997-12-17,8974673827 9788974673826,http://book.naver.com/bookdb/book_detail.php?b...,JavaScript,1997
6420,"모던웹 디자인을 위한 HTML5+CSS3입문, Javascript+jQuery 입문...",NaN,한빛미디어,62000,62000,2013-10-29,3102900046 9783102900041,http://book.naver.com/bookdb/book_detail.php?b...,JavaScript,2013
6421,JAVASCRIPT IN A WEEK,ARMAN DANESH,인포북,36000,36000,1998-06-01,1575210738 9781575210735,http://book.naver.com/bookdb/book_detail.php?b...,JavaScript,1998

In [56]:
langs_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 6417 entries, 0 to 6421
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   제목      6417 non-null   object
 1   저자      6410 non-null   object
 2   출판사     6417 non-null   object
 3   가격      6417 non-null   int64
 4   할인 가격   6417 non-null   int64
 5   출간일     6417 non-null   object
 6   isbn    6416 non-null   object
 7   링크      6417 non-null   object
 8   언어      6417 non-null   object
 9   출간년도    6417 non-null   int64
dtypes: int64(3), object(7)
memory usage: 551.5+ KB

In [57]:
langs_df.isnull().sum()

제목       0
저자       7
출판사      0
가격       0
할인 가격    0
출간일      0
isbn     1
링크       0
언어       0
출간년도     0
dtype: int64

- 결측치의 수가 적기 때문에 일단 이 값들은 제외하고 분석을 이어나가겠다.

In [58]:
langs_df.dropna(inplace=True)
langs_df.isnull().sum()

제목       0
저자       0
출판사      0
가격       0
할인 가격    0
출간일      0
isbn     0
링크       0
언어       0
출간년도     0
dtype: int64

In [59]:
langs_df.reset_index(drop=True, inplace=True)
langs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6409 entries, 0 to 6408
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   제목      6409 non-null   object
 1   저자      6409 non-null   object
 2   출판사     6409 non-null   object
 3   가격      6409 non-null   int64
 4   할인 가격   6409 non-null   int64
 5   출간일     6409 non-null   object
 6   isbn    6409 non-null   object
 7   링크      6409 non-null   object
 8   언어      6409 non-null   object
 9   출간년도    6409 non-null   int64
dtypes: int64(3), object(7)
memory usage: 500.8+ KB

In [60]:
langs_df['언어'].unique()

array(['python', 'Java', 'C', 'C++', 'C#', 'Visual Basic', 'SQL', 'PHP',
       'R', 'JavaScript'], dtype=object)

#### 이제 두 데이터프레임을 병합해보자.

In [61]:
len(langs_df)

6409

In [62]:
len(langs_df2)

777

In [63]:
langs_df = pd.concat([langs_df, langs_df2], ignore_index=True)
langs_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7186 entries, 0 to 7185
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   제목      7186 non-null   object
 1   저자      7186 non-null   object
 2   출판사     7186 non-null   object
 3   가격      7186 non-null   int64
 4   할인 가격   7186 non-null   int64
 5   출간일     7186 non-null   object
 6   isbn    7186 non-null   object
 7   링크      7186 non-null   object
 8   언어      7186 non-null   object
 9   출간년도    7186 non-null   int64
dtypes: int64(3), object(7)
memory usage: 561.5+ KB

In [64]:
langs_df['언어'].unique()

array(['python', 'Java', 'C', 'C++', 'C#', 'Visual Basic', 'SQL', 'PHP',
       'R', 'JavaScript', 'Assembly language', 'Go', 'MATLAB', 'Groovy',
       'Ruby', 'Swift', 'Fortran', 'Perl', 'Delphi'], dtype=object)

- 20개 언어관련 도서들의 데이터를 전부 불러온 것 같고, Classic Visual Basic이 없는거로 보아 국내도서에는 관련 도서가 없는 것 같다.

#### 혹시 병합한 이 두 데이터프레임간의 중복데이터가 있는지 확인해보자.

In [65]:
len(langs_df['isbn'].unique())

6724

In [66]:
len(langs_df)

7186

- csv로 불러온 데이터도 이미 중복데이터를 isbn으로 정리하였고,
- 추가적으로 생성한 상위 20위까지의 언어 관련 도서데이터도 isbn으로 중복데이터로 정리해주었기 때문에,
- 병합한 데이터에서 나타난 중복데이터는 두개 이상의 언어와 관련된 도서라고 생각하고 분석을 진행하기로 하였다.

#### 책 가격에 대한 데이터는 수집하였으므로, 추가적으로 페이지수 데이터를 수집해야한다.

In [67]:
langs_df.tail(3)

,제목,저자,출판사,가격,할인 가격,출간일,isbn,링크,언어,출간년도
7183,알기쉬운 델파이 2.0,주병진,정보문화사,18000,18000,1996-11-09 00:00:00,897627282X 9788976272829,http://book.naver.com/bookdb/book_detail.php?b...,Delphi,1996
7184,정보처리산업기사 실기 (델파이),주병진,정보문화사,10000,10000,1999-01-11 00:00:00,8976275284 9788976275288,http://book.naver.com/bookdb/book_detail.php?b...,Delphi,1999
7185,델파이 2 (21일완성),DAN OSIER,인포북,18000,18000,1997-06-10 00:00:00,8980542712 9788980542710,http://book.naver.com/bookdb/book_detail.php?b...,Delphi,1997

- 책 페이지수 데이터는 왠지 링크에 접속하면 구할 수 있을 것 같아 임의의 링크 하나에 접속해보았다.

In [68]:
langs_df.iloc[0, 7]

'http://book.naver.com/bookdb/book_detail.php?bid=16439154'

![page](../data/page.png)

- 페이지수에 대한 태그를 불러오면 전체 데이터에 대한 페이지수를 모두 구할 수 있다.
- 네이버 책 도서 페이지 수 태그
- #container > div.spot > div.book_info > div.book_info_inner > div:nth-child(3)

#### 그런데 예외가 있을 수 있지 않을까?

In [69]:
langs_df.iloc[len(langs_df)-1, 7]

'http://book.naver.com/bookdb/book_detail.php?bid=57577'

![page2](../data/page2.png)

- 페이지수 위에 원제가 있는 책들이 있다.
- 따라서 예외처리를 다른 태그값으로 해줘야한다.
- 네이버 책 도서 페이지 수 태그 (원제가 있는 경우)
- #container > div.spot > div.book_info > div.book_info_inner > div:nth-child(4)

In [70]:
import ssl

In [71]:
from bs4 import BeautifulSoup

# from urllib.request import urlopen
from urllib.request import Request, urlopen

url = 'https://book.naver.com/bookdb/book_detail.naver?bid=16439154'

# html = urlopen(url)

req = Request(url, headers={'User-Agent' : 'Chrome'})
context = ssl._create_unverified_context()
html = urlopen(req, context=context).read()
soup = BeautifulSoup(html, 'html.parser')

#### 테스트로 페이지수에 대한 태그값을 불러와서 페이지수만 뽑아내보자.

In [72]:
soup.select('#container > div.spot > div.book_info > div.book_info_inner > div:nth-child(3)')[0].text.split()[1].split('|')[0]

'604'

#### 원제가 있는 도서에 대해서도 페이지수를 불러와보자.

In [73]:
url = 'http://book.naver.com/bookdb/book_detail.php?bid=57577'

# html = urlopen(url)

req = Request(url, headers={'User-Agent' : 'Chrome'})
context = ssl._create_unverified_context()
html = urlopen(req, context=context).read()
soup = BeautifulSoup(html, 'html.parser')

In [74]:
soup.select('#container > div.spot > div.book_info > div.book_info_inner > div:nth-child(4)')[0].text.split()[1].split('|')[0]

'712'

#### 이제 반복문을 통해 모든 도서의 링크에 대해서 페이지수를 불러오자.

In [75]:
from tqdm import tqdm_notebook

In [76]:
link_list = list(langs_df['링크'])
page_list = []

for link in tqdm_notebook(link_list):
    url = link
    req = Request(url, headers={'User-Agent' : 'Chrome'})
    context = ssl._create_unverified_context()
    html = urlopen(req, context=context).read()
    soup = BeautifulSoup(html, 'html.parser')
    try:
        a = soup.select('#container > div.spot > div.book_info > div.book_info_inner > div:nth-child(3)')[0].text.split()[1].split('|')[0]   
        page_list.append(a)
    except:
        continue

    # 조건문을 조금 더 손봐야겠다.

  0%|          | 0/7186 [00:00<?, ?it/s]